import * as AS from "../index";

(async function () { 
	const t = AS.Task<string>()
		.tokenize("")
		.print("1")
		.each()
		.print("2")
		.fn(x => x.length)
		.print("3")
		.fn(x => [x, 1, 2, 3, 4, "abcd"])
		.print("4")
		.map(x => x.toString())
		.print("5")
		.filterArray(x => x.length < 2)
		.print("6")
		.flat()
		.print("7")
		.reduce(x => parseInt(x))
		.print("8")
		.fn(x => [x, 1, 2, 2, 3, 4, "abcd"])
		.print("9")
		.countInArray(x => x)
		.print("10")
		.fn(x => Object.values(x))
		.print("11")
		.flat()
		.print("12")

	t.inject("i tipi sono belli e mi fanno sentire più sicuro anche con javascript")
})()
